# Generated by Django 6.0.5 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polytechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.CharField(max_length=100)),
                ('specialization', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='specialization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='degree',
            name='sub_course',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intermediate_courses',
            name='specialization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='iti',
            name='specialization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pg_courses',
            name='specialization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ug_courses',
            name='specialization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vocational_courses',
            name='specialization',
            field=models.TextField(),
        ),
    ]
