# Generated by Django 6.0.5 on 2026-05-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='questions_ready',
            field=models.BooleanField(default=False),
        ),
    ]
