# Generated by Django 6.0.5 on 2026-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_university_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='hr_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
