# Generated by Django 6.0.5 on 2026-05-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hr_hr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='hr_id',
            new_name='id_no',
        ),
    ]
