# Generated by Django 6.0.5 on 2026-05-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_hr_id_hr_id_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='id_no',
            new_name='hr_id',
        ),
    ]
