# Generated by Django 6.0.5 on 2026-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_industrysector_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
