# Generated by Django 6.0.5 on 2026-05-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
