# Generated by Django 6.0.5 on 2026-05-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_employer_employer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.hr'),
        ),
    ]
