# Generated by Django 6.0.5 on 2026-05-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_studentprofile_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id_no',
        ),
    ]
