# Generated by Django 6.0.5 on 2026-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_studentprofile_id_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
