# Generated by Django 6.0.5 on 2026-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_payment_status_payment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.CharField(db_index=True, max_length=50)),
                ('org', models.CharField(choices=[('Hospitals', 'Hospitals'), ('Schools', 'Schools'), ('Colleges', 'Colleges'), ('IT Industry', 'IT Industry'), ('Hardware Industry', 'Hardware Industry'), ('Service Sector', 'Service Sector'), ('Banks', 'Banks'), ('Retail Sector', 'Retail Sector'), ('Logistics', 'Logistics')], max_length=80)),
                ('role', models.CharField(choices=[('Administration', 'Administration'), ('Engineer', 'Engineer'), ('Faculty', 'Faculty'), ('Nursing', 'Nursing'), ('Librarian', 'Librarian'), ('Developer', 'Developer'), ('Support', 'Support'), ('Clerk', 'Clerk'), ('Technician', 'Technician'), ('System Admin', 'System Admin'), ('Accountant', 'Accountant'), ('Security', 'Security'), ('HR Manager', 'HR Manager'), ('Data Analyst', 'Data Analyst'), ('Quality Tester', 'Quality Tester'), ('Sales Officer', 'Sales Officer'), ('Store Manager', 'Store Manager'), ('Driver', 'Driver'), ('Warehouse Staff', 'Warehouse Staff'), ('Supply Chain Mgr', 'Supply Chain Mgr'), ('Doctor', 'Doctor'), ('Counselor', 'Counselor')], max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('salary', models.CharField(blank=True, max_length=80)),
                ('available_jobs', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
    ]
