# Generated by Django 6.0.5 on 2026-05-30 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_jobposting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={},
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='available_jobs',
            new_name='vacancies',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hr',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='accounts.employer'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='org',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='role',
            field=models.CharField(max_length=150),
        ),
    ]
