# Generated by Django 6.0.5 on 2026-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_jobposting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
