# Generated by Django 6.0.5 on 2026-06-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_jobposting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_stack', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('section', models.CharField(choices=[('Personal', 'Personal'), ('Technical', 'Technical'), ('Professional', 'Professional')], db_index=True, max_length=20)),
                ('question', models.TextField()),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tech_stack', 'designation', 'specialization', 'section'], name='accounts_qu_tech_st_aec994_idx')],
            },
        ),
    ]
