# Generated by Django 6.0.5 on 2026-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_questionbank'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionbank',
            name='accounts_qu_tech_st_aec994_idx',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='job_interest',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['tech_stack', 'designation', 'section'], name='accounts_qu_tech_st_f8fe8d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['job_interest', 'section'], name='accounts_qu_job_int_d94bed_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['experience_level', 'section'], name='accounts_qu_experie_3fa0d0_idx'),
        ),
    ]
